---
# This role creates an advanced iApp service
# - http virtual server
# references.yaml creates
# - Service Discovery iApp to discover pool members in AWS
# - Logging Profiles
# - LTM policy 
# - WAF policy

- name: Install iApp Template for Virtual Service Insertion
  bigip_iapp_template:
    state: "present"
    content: "{{ lookup('file', iApp_template_name + '.tmpl') }}"
    force: yes
  delegate_to: localhost

# Add all dependent objects
- include: references.yaml
  delegate_to: localhost

# Generate the iApp we will deploy from a template 
- name: Modify Virtual Service iApp Payload to interpolate variables
  template: src="{{ jinja_template_name }}" dest="{{ install_path }}/state_cache/{{ deploymentName }}/iApp-{{ iApp_service_name }}.json"
  delegate_to: localhost

- name: Deploy Virtual Service iApp 
  delegate_to: localhost
  bigip_iapp_service:
      state: "present"
      partition: "{{partition}}"
      name: "{{ iApp_service_name }}"
      template: "/Common/{{ iApp_template_name }}"
      parameters: "{{ lookup('file', install_path + '/state_cache/' + deploymentName + '/iApp-' + iApp_service_name + '.json') }}"
      strict_updates: "{{ strict_updates }}"

  register: result

